language: python
matrix:
  include:
    # Python 2.7
    - env: TOXENV=py27
      python: 2.7
    # Python 3.5
    - env: TOXENV=py35
      python: 3.5
    # Python 3.6
    - env: TOXENV=py36
      python: 3.6
    # Python 3.7
    - env: TOXENV=py37
      python: 3.7
      dist: xenial
    # SQLAlchemy 1.3
    - env: TOXENV=py37-sql13
      python: 3.7
      dist: xenial
    # Pre-commit
    - env: TOXENV=pre-commit
      python: 3.7
      dist: xenial
install: pip install .[dev]
script: tox
after_success: coveralls
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/pre-commit
deploy:
  provider: pypi
  user: syrusakbary
  on:
    tags: true
  password:
    secure: q0ey31cWljGB30l43aEd1KIPuAHRutzmsd2lBb/2zvD79ReBrzvCdFAkH2xcyo4Volk3aazQQTNUIurnTuvBxmtqja0e+gUaO5LdOcokVdOGyLABXh7qhd2kdvbTDWgSwA4EWneLGXn/SjXSe0f3pCcrwc6WDcLAHxtffMvO9gulpYQtUoOqXfMipMOkRD9iDWTJBsSo3trL70X1FHOVr6Yqi0mfkX2Y/imxn6wlTWRz28Ru94xrj27OmUnCv7qcG0taO8LNlUCquNFAr2sZ+l+U/GkQrrM1y+ehPz3pmI0cCCd7SX/7+EG9ViZ07BZ31nk4pgnqjmj3nFwqnCE/4IApGnduqtrMDF63C9TnB1TU8oJmbbUCu4ODwRpBPZMnwzaHsLnrpdrB89/98NtTfujdrh3U5bVB+t33yxrXVh+FjgLYj9PVeDixpFDn6V/Xcnv4BbRMNOhXIQT7a7/5b99RiXBjCk6KRu+Jdu5DZ+3G4Nbr4oim3kZFPUHa555qbzTlwAfkrQxKv3C3OdVJR7eGc9ADsbHyEJbdPNAh/T+xblXTXLS3hPYDvgM+WEGy3CytBDG3JVcXm25ZP96EDWjweJ7MyfylubhuKj/iR1Y1wiHeIsYq9CqRrFQUWL8gFJBfmgjs96xRXXXnvyLtKUKpKw3wFg5cR/6FnLeYZ8k=
  distributions: "sdist bdist_wheel"
